/* scale(缩放)
opacity(透明度)
color(颜色)
x(x轴)
y(y轴)
y(y轴)
rotate(旋转)
duration(持续时间)
borderRadius(圆角)
delay 延时(秒)
delayChildren 子组件延时(秒)
spring(拟物曲线动画)
drag(是否可拖动)
staggerChildren 错开(若为0.01，第一个孩子将被延迟0秒，第二个孩子将被延迟0.01，第三个孩子将被延迟0.02，依此类推)
when: false | "beforeChildren" | "afterChildren" |(时间顺序)
repeat: Infinity |数字 |(循环次数)
repeat: loop从头到尾,reverse反向循环,mirror交替循环 |(循环状态)
repeatDelay|(循环延时)
linear(线性匀速动画)
tween(补间动画)
linear:cubic bezier curve贝塞尔曲线(贝塞尔曲线) 贝塞尔曲线子项:"ease"、"linear"、"easeIn"、"easeOut"、"easeInOut"、"circIn"、"circOut"、"circInOut"、"backIn"、"backOut"、"backInOut"、"anticipate"
from(关键帧断点)
times: [0.1, 0.1, 0.1, 0.1](关键帧持续时间)
bounce(弹力)
damping(阻尼,会覆盖bounce,duration)
mass(缓动,会覆盖bounce,duration)
stiffness(刚度,会覆盖bounce,duration)
velocity(初速度)
restSpeed(低速结束动画)
restDelta(距离结束动画)
inertia(惯性曲线动画，可与velocity初速度配合使用)
modifyTarget(网格运动)
bounceStiffness(弹力刚度)
bounceDamping(弹力阻尼)
power(拖拽准心准确度,值越大准确度越高)
timeConstant(减速时间)
transition(过度)
transitionEnd(结束过度方式)
useTransform(联动)
start(开始)
stop(停止)
await(异步动画)
layout(布局动画)
useSpring(曲线监测)
useVelocity(速度监测) */
import React, { useState } from "react";
